version: '3.8'

services:
  risksim-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://hamza:hamza@cluster0.n44j3.mongodb.net/risk_simulation
      - DATABASE_NAME=risk_simulation
      - SECRET_KEY=1q2w3e
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - REFRESH_TOKEN_EXPIRE_DAYS=70
      - BASE_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:5173
    restart: unless-stopped